### ISSUE TITLE
Option for "raw" logging

### ISSUE THREAD

**Issue by erikgb** [senseyeio/udplogger#1]
This image is super:
- Ultra small
- Well documented
- Well made

Thanks a lot!

But I would love to have an option to run it in "raw" mode. This is because my client application is sending JSON-formatted messages to the logger, and the prefix added to each log statement makes the output in stdout invalid JSON.

#### Given message
`{ "name":"John", "age":30, "car":null }`

#### Actual output in stdout
`2019-10-07T15:57:27.949Z received: "{ \"name\":\"John\", \"age\":30, \"car\":null }"`

#### Expected output in stdout
`{ "name":"John", "age":30, "car":null }`

Are you accepting PR?

**Comment by alcortesm** [comment]
Thanks for opening this issue @erikgb . Yes, we accept PRs :).

Adding a raw mode would be a nice improvement. Please let me know if you need help with it.

What do you think would be the best way to activate raw mode? Do you think a command-line flag would make sense in this case?

**Comment by erikgb** [comment]
@alcortesm Thanks for you prompt response! I am glad to see that this open sourced image is "alive".

Well, I am a Java developer, but code is code. ;-) I haven't done any Go coding so far, but this might just be the opportunity I need to get **go**ing.

We are running the image in a Kubernetes based environment. And the most conventient/natural way of configuring a Kubernetes container is through environment variables. But I understand your suggestion on configuring this through a command-line flag.
One idea could be to allow for some kind of "format" environment variable, but that seems a bit over-complicated.
What about an environment variable named "LOGGER_MODE" (enumerated)? The challenge is to come up with the enumerated value set....

Please advise. :-)

**Comment by alcortesm** [comment]
@erikgb I'm okay with making it an environment variable too, à la 12-factor app. That way people will be able to change that easily between deployments environments (dev, test, prod...). It is just I wasn't sure this is something people want to change between envs.

Let's go with something short and simple for now, a RAW environment variable:
1. When its value is "on", raw output is produced (new behaviour).
2. When its value is "off", escaped output with timestamps are produced (old behaviour).
3. If the environment variable is missing, assume it is "off".
4. Any other value will produce an error, "unknown environment setting RAW=foo".

This should look natural to gophers (see how the GO111MODULE env var works for example) and it is simple enough for other users too.

What do you think?

Regarding code changes: Go is a simple language and the existing code is quite short, but you will need to get familiar with some stdlib packages we are using. Please let me know if I can help you in any way. Here is a short review of the code in case it helps you:

You will find the entry point for the command at cmd/udplogger/main.go. The code there uses some packages from the stdlib and the code in package udplogger itself (at the root of this repo). 

Package udplogger is supposed to contain all the functionality of the program and main.go should just have some basic stuff about how to call the command, but right now it is the other way around due to historical reasons: main.go contains the main functionality and package updlogger handles the details about how to parse environment variables :). I'm planning to fix that in the future, but right now, it is best to just go with that.

Following this rationale, my suggestion is to add a new Raw function to the udplogger package, returning (bool, error). Then call that from main to return an error or configure the logger to do the right thing. You might also want to stop using the `%q` verb when printing when RAW is enabled, you can handle it with a simple if or make the logger a little bit more intelligent so it can handle those details by itself (I would just use an `if` if this were my first Go program, I will later refactor things to create an udplogger.Log type that logs UDP payloads according to the configuration).

**Comment by erikgb** [comment]
@alcortesm Thanks for your input. I have now forked the repository and will prepare a PR. Let's just see what I can come up with and take it from there. :-)

**Comment by alcortesm** [comment]
Hi @erikgb , thank you for your contribution.

The `latest` tag in dockerhub already includes your changes, see https://hub.docker.com/r/senseyeio/udplogger/tags.

Enjoy!

**Comment by erikgb** [comment]
@alcortesm Thanks for following up! I am running with the latest tag from Docker Hub now, and everything works as expected. 👍
